version: "3.4"

# extensions
x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
    args:
      ARTIFACT: "${artifact_url}"
    x-bake:
      platforms:
        - linux/amd64
        - linux/arm64
  image: "${repo}:latest"
x-jdk: &jdk
  build:
    context: .
    dockerfile: Dockerfile-jdk
    args:
      ARTIFACT: "${artifact_url}"
    x-bake:
      platforms:
        - linux/amd64      
        - linux/arm64
  image: "${repo}:latest-jdk"
x-zulu-alpine: &zulu-alpine
  build:
    context: .
    dockerfile: Dockerfile-zulu-alpine
    args:
      ARTIFACT: "${artifact_url}"
    x-bake:
      platforms:
        - linux/amd64    
        - linux/arm64
  image: "${repo}:latest-zulu-alpine"
x-zulu-alpine-jdk: &zulu-alpine-jdk
  build:
    context: .
    dockerfile: Dockerfile-zulu-alpine-jdk
    args:
      ARTIFACT: "${artifact_url}"
    x-bake:
      platforms:
        - linux/amd64  
        - linux/arm64
  image: "${repo}:latest-zulu-alpine-jdk"

# images
services:
  zulu-alpine-jdk-minor:
    << : *zulu-alpine-jdk
    image: "${repo}:${minor}-zulu-alpine-jdk"
  zulu-alpine-jdk-major:
    << : *zulu-alpine-jdk
    image: "${repo}:${major}-zulu-alpine-jdk"
  zulu-alpine-jdk-latest:
    *zulu-alpine-jdk

  zulu-alpine-minor:
    << : *zulu-alpine
    image: "${repo}:${minor}-zulu-alpine"
  zulu-alpine-major:
    << : *zulu-alpine
    image: "${repo}:${major}-zulu-alpine"
  zulu-alpine-latest:
    *zulu-alpine

  jdk-minor:
    << : *jdk
    image: "${repo}:${minor}-jdk"
  jdk-major:
    << : *jdk
    image: "${repo}:${major}-jdk"
  jdk-latest:
    *jdk

  base-minor:
    << : *base
    image: "${repo}:${minor}"
  base-major:
    << : *base
    image: "${repo}:${major}"
  base-latest:
    *base
